package Helden

open class Helden{

    open var faehigkeiten = mutableListOf<String>()
    open fun showFaehigkeiten(){
        println(faehigkeiten)
    }

    open var heldenArt: String = ""

    val heldenListe = listOf<String>("Helden.Magier", "Helden.Ritter", "Helden.Mönch")
    val heldenHP: IntRange = 300..500
    open val heldenNamen = mutableListOf<String>(
        "Eltrocus",
        "Kid",
        "Bat",
        "Dazzler",
        "Crow",
        "Spitfire",
        "Watcher",
        "Whiz",
        "Oxman",
        "Mole",
        "Puma",
        "Wolfman",
        "Blitzfire",
        "Deadnite",
        "Whiz",
        "General",
        "Katana",
        "Colossus",
        "Shield",
        "Spider",
        "Prophet",
        "Girl",
        "Wolfman",
        "Nighthawk",
        "One",
        "Wildflame",
        "Hope",
        "Kid",
        "Wonder",
        "Trident",
        "Chronos",
        "Y",
        "Scout",
        "Razor",
        "Dagger",
        "Manta",
        "Griffin",
        "Flare",
        "Archer",
        "Slayer",
        "Soldier",
        "Illusionist",
        "Savior",
        "Spy",
        "Vindicator",
        "Amazon",
        "General",
        "Leopard",
        "Knuckles",
        "Protector",
        "Gamma",
        "Mercenary",
        "Karma",
        "Grasshopper",
        "Granite",
        "Phantasm",
        "Nightquake",
        "Magician",
        "Optimo",
        "Prophet",
        "Guardian",
        "Spectre",
        "Atomic",
        "Axeman",
        "Gargoyle",
        "Starlight",
        "Armadillo",
        "Shield",
        "Warrior",
        "Siren",
        "Saber",
        "Marksman",
        "Hammer",
        "Elemental",
        "Roach",
        "Venombite",
        "Commander",
        "Commander",
        "Katana",
        "Watcher",
        "Spitfire",
        "Wonderman",
        "Mole",
        "Knight",
        "Halo",
        "Manta",
        "Nightowl",
        "Dragonloom",
        "Beetle",
        "Sentinel",
        "Incognito",
        "Crusher",
        "Sage",
        "Rosethorn",
        "Oxman",
        "Remix",
        "Nighthawk",
        "Spitfire",
        "Gladiator",
        "Flame"
    )
    open val faehigkeitsSchaden: IntRange = 35..70

}